name: Build & Test Caddy Plugin

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build plugin
        run: go build ./...
      - name: Test plugin
        run: go test -v ./... || echo "No tests found — skipping"
